name: autorun
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 15 * * 1'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run code
        run: git clone https://github.com/luolongfei/freenom.git  && cd freenom && cp .env.example .env && echo  -e "FREENOM_PASSWORD='${{secrets.PASSWORD}}'\nMULTIPLE_ACCOUNTS='${{secrets.USERNAME}}'" >> .env && cat .env && php run
