name: autorun
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 15 * * 1'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run code
        run: git clone https://github.com/luolongfei/freenom.git  && cd freenom && cp .env.example .env && echo  "FREENOM_PASSWORD='${{secrets.USERNAME}}' \n MULTIPLE_ACCOUNTS='${{secrets.PASSWORD}}'" >> .env  && php run
