name: autorun
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 15 * * 1'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run code
        run: git clone https://github.com/star574/freenom.git && cd freenom && chmod +x ./run.sh && ./run.sh
