name: autorun
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 15 * * 1'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run code
        run: docker run -d --name freenom  -v $(pwd):/conf -v $(pwd)/logs:/app/logs luolongfei/freenom && sed -i "19d" .env && sed -i "21d" .env && echo  -e "FREENOM_PASSWORD='${{secrets.PASSWORD}}'\nFREENOM_ACCOUNTS='${{secrets.USERNAME}}'" >> .env   && cat .env && docker restart freenom && docker logs freenom && tail -f ./logs/freenom_cron.log
