name: autorun
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 15 * * 1'

jobs:
  autorun:
    runs-on: centos7
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run code
        run: mkdir -p /data/wwwroot/freenom && cd /data/wwwroot/freenom && git clone https://github.com/luolongfei/freenom.git ./ && cd /data/wwwroot/freenom/ && php run
